### ISSUE TITLE
User interface clarity

### ISSUE THREAD

**Issue by bartfaitamas** [neelix-io/neelix-experiences#3] opened 2020-12-10 08:46 UTC
The first time I was using the software during a retrospective meeting, I voted on the wrong item accidentally. It was a bit hard to find visual cues, which UI item belongs to where.
I'm not a UX expert, but I think some more contrast around the different items would help. Also, more visual aid for the actions/buttons to make it clearer to which items they belong to.

**Comment by neelix-admin** [comment] 2020-12-10 08:53
Hi Tamas, based on the observation from the Retro, the mistake you are talking about is probably caused by action buttons being located at the bottom the feedback item. Improvements that would help with such scenarios are:
- Move action buttons to the top of the feedback item
- Consider a more prominent border around the feedback card, as opposed to a shaded block
Thank you for your feedback.

**Comment by neelix-admin** [comment] 2020-12-10 20:52
Update to feedback cards layout is deployed in production. We will monitor feedback from other users before closing this ticket.

**Comment by neelix-admin** [comment] 2020-12-17 00:55
Additional feedback is now incorporated and deployed to production. We thank all contributors in polishing up retro-point flow.

**Closed as completed by neelix-admin** 2020-12-17 00:55 UTC
Labels: enhancement, retrospective
